// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcKcWJT3wMFBQ1nM_gXu_0IQlXGzdsXyo',
    appId: '1:1055441681418:web:e9946d36349d6e3bc373f3',
    messagingSenderId: '1055441681418',
    projectId: 'wechat-b30fd',
    authDomain: 'wechat-b30fd.firebaseapp.com',
    storageBucket: 'wechat-b30fd.firebasestorage.app',
    measurementId: 'G-SJ2S8PD1HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYKkCVX3LvuHXB8MtyVJl5b96IU5RMAH0',
    appId: '1:1055441681418:android:940b792847b25cdfc373f3',
    messagingSenderId: '1055441681418',
    projectId: 'wechat-b30fd',
    storageBucket: 'wechat-b30fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDem-S-qP6C7A1OL2fuyRtSFBBnQrQVpWA',
    appId: '1:1055441681418:ios:3fa834ef72088e7ac373f3',
    messagingSenderId: '1055441681418',
    projectId: 'wechat-b30fd',
    storageBucket: 'wechat-b30fd.firebasestorage.app',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );
}
